services:
  spoofdpi:
    image: ghcr.io/bariiss/spoofdpi:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spoofdpi
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8080:8080"
    networks:
      spoofdpi:
    command: >
      --window-size 1
      --port 8080
      --addr 0.0.0.0
      --enable-doh
      --dns-addr 77.88.8.8
      --dns-port 53
      --system-proxy false
      --debug false

networks:
  spoofdpi:
    name: spoofdpi